name: UseOfSimpleAction
on: push

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: files before checkout
        run: |
           ls -l

      - name: git-checkout 
        id: checkout 
        uses: actions/checkout@v3

      - name: files after checkout
        run: ls -l 
        