name: UseOfSimpleAction
on: push

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: before check out
        run: ls -l
      - name: check out
        uses: actions/checkout@v3
      - name: after check out
        run: ls -l

        