name: workdingdirectories
on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: list the files before checkout
        run: ls -al
      - name: Simple JS action
        id: checkout
        uses: actions/checkout@v4
      - name: list the files after checkout
        run: ls -al
    