name: firstworkflow1
on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "Hello Tech Evo team, Welcome to GitHub actions world1"
            ls -al
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:  
      - name: step1
        run: echo "Run after first job runs"