name: HelloToGitHubActions
on: push

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: name1
        run: |
           ls -l
           echo "hello"
  paralleljob:
    runs-on: windows-latest
    steps:
      - name: name2
        run: ping 
     